before_script:
  - psql -c 'create database pulse_test;' -U postgres
language: ruby
rvm:
  - 2.2.3
script: bundle exec rspec
env:
  global:
    - GRAPHITE_URL=http://graphite.wikidot.com
    - GRAPHITE_USERNAME=test
    - GRAPHITE_PASSWORD=test
