# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 016d83089833bf62087372eeff9f254d851ed422880a24bc59294962189b3d98f4b9acac5211ca9686751478bd45ee994e61ab8fce95596b5b32f52d49fb26b1

test:
  secret_key_base: 606339d2fa8d866da65849d17b79b92e990036545615280174ff3308cee91aed2ac88d938cf77a98c38e7a5ba9547b3c13b0d90d84024a2ed733c7212fc81c0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
